name: Build site

on:
  push:
    branches: [ "src" ]
  pull_request:
    branches: [ "src" ]

permissions:
  contents: read

jobs:

  buildsite:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Deploy Nikola to GitHub Pages
      uses: getnikola/nikola-action@v8
